
package clients;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.4-b01-
 * Generated source version: 2.1
 * 
 */
@WebService(name = "SOAPServerInterface", targetNamespace = "http://servers/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SOAPServerInterface {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "viewcart", targetNamespace = "http://servers/", className = "clients.Viewcart")
    @ResponseWrapper(localName = "viewcartResponse", targetNamespace = "http://servers/", className = "clients.ViewcartResponse")
    public String viewcart(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "additemtocart", targetNamespace = "http://servers/", className = "clients.Additemtocart")
    @ResponseWrapper(localName = "additemtocartResponse", targetNamespace = "http://servers/", className = "clients.AdditemtocartResponse")
    public String additemtocart(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "removefromcart", targetNamespace = "http://servers/", className = "clients.Removefromcart")
    @ResponseWrapper(localName = "removefromcartResponse", targetNamespace = "http://servers/", className = "clients.RemovefromcartResponse")
    public String removefromcart(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "flightList", targetNamespace = "http://servers/", className = "clients.FlightList")
    @ResponseWrapper(localName = "flightListResponse", targetNamespace = "http://servers/", className = "clients.FlightListResponse")
    public String flightList(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buyitems", targetNamespace = "http://servers/", className = "clients.Buyitems")
    @ResponseWrapper(localName = "buyitemsResponse", targetNamespace = "http://servers/", className = "clients.BuyitemsResponse")
    public String buyitems(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

}
