web: newrelic-admin run-program gunicorn -w 4 server:app
worker: celery -A celery_tasks.celery worker --loglevel=info --without-gossip --without-mingle --without-heartbeat
clock: python background_scheduler.py